CREATE TABLE IF NOT EXISTS WALLET (
ID VARCHAR(50) PRIMARY KEY,
VERSION INT,
CURRENCY VARCHAR(10) NOT NULL,
BALANCE DECIMAL(10,2) NOT NULL,
CREATE_TMS TIMESTAMP NOT NULL,
UPDATE_TMS TIMESTAMP NOT NULL
);

INSERT INTO WALLET (ID,VERSION,CURRENCY,BALANCE,CREATE_TMS,UPDATE_TMS) VALUES ('1',0,'EURO',100.50,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WALLET (ID,VERSION,CURRENCY,BALANCE,CREATE_TMS,UPDATE_TMS) VALUES ('2',0,'EURO',500,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO WALLET (ID,VERSION,CURRENCY,BALANCE,CREATE_TMS,UPDATE_TMS) VALUES ('3',0,'EURO',320.80,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO WALLET (ID,VERSION,CURRENCY,BALANCE,CREATE_TMS,UPDATE_TMS) VALUES ('4',0,'EURO',210.35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS TRANSACTION (
ID BIGINT NOT NULL,
WALLET_ID VARCHAR(100) NOT NULL,
TXN_TYPE VARCHAR(10) NOT NULL,
AMOUNT DECIMAL(10,2) NOT NULL,
CURRENCY VARCHAR(10) NOT NULL,
TXN_TMS TIMESTAMP NOT NULL,
FOREIGN KEY(WALLET_ID) REFERENCES WALLET(ID)
);